#!/usr/bin/env bash

# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# collect start up details
echo "> **/prepare.sh"
find . -name prepare.sh | while read installer ; do printf "\n$installer\n"; source "${installer}" ; done; printf "\n\n"

# set up root dependencies
echo "> **/pre-install.sh"
find . -name pre-install.sh | while read installer ; do printf "\n$installer\n"; sh -c "${installer}" ; done; printf "\n\n"

# install preferred software
echo "> **/install.sh"
find . -name install.sh | while read installer ; do printf "\n$installer\n"; sh -c "${installer}" ; done; printf "\n\n"

# clean up and apply any final glue or finsih
echo "> **/post-install.sh"
find . -name post-install.sh | while read installer ; do printf "\n$installer\n"; sh -c "${installer}" ; done; printf "\n\n"
