#!/usr/bin/env bash

# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "› brew bundle"
brew bundle --file=./Brewfile

# Find the installers and run them iteratively
echo "> script/install"
find . -name install.sh | while read installer ; do echo $installer; sh -c "${installer}" ; done

# Run Homebrew through the Brewfile
echo "› brew bundle casks"
brew bundle --file=./homebrew/casks.rb

echo "› brew bundle mas"
brew bundle --file=./homebrew/mas.rb